DROP TABLE ACCOUNTS;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;
DROP TABLE REIMBURSEMENT;
DROP TABLE MANAGER_SERVICE;

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    FIRSTNAME VARCHAR2(100),
    LASTNAME VARCHAR2(100),
    USERNAME VARCHAR2(100) NOT NULL,
    PASS_WORD VARCHAR2(100) NOT NULL,
    MANAGER_ID INTEGER NOT NULL
);
/
CREATE TABLE REIMBURSEMENT(
  REIM_ID INTEGER PRIMARY KEY,
  EMPLOYEE_ID INTEGER NOT NULL,
  IMAGE BLOB,
  AMOUNT NUMBER(6,2) DEFAULT 0.00,
  DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  MANAGER_ID INTEGER NOT NULL,
  STATUS NUMBER(1) NOT NULL
);
/
CREATE TABLE MANAGER_SERVICE(
    MANAGER_ID INTEGER NOT NULL,
    REIM_ID INTEGER NOT NULL,
    DECISION NUMBER(1),
    DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);